### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by yukiinagato** [RicterZ/BGmi#2]
```
ox@ox-Kaizaki:~/BGmi$ sudo bgmi cal all
Sun. 
---------------------------------   ---------------------------------   
Traceback (most recent call last):
  File "/usr/local/bin/bgmi", line 11, in <module>
    load_entry_point('bgmi==0.4.5', 'console_scripts', 'bgmi')()
  File "/home/ox/.local/lib/python2.7/site-packages/bgmi-0.4.5-py2.7.egg/bgmi/main.py", line 409, in setup
    main()
  File "/home/ox/.local/lib/python2.7/site-packages/bgmi-0.4.5-py2.7.egg/bgmi/main.py", line 178, in main
    cal(ret)
  File "/home/ox/.local/lib/python2.7/site-packages/bgmi-0.4.5-py2.7.egg/bgmi/main.py", line 346, in cal
    bangumi_calendar(force_update=force, today=today, save=save)
  File "/home/ox/.local/lib/python2.7/site-packages/bgmi-0.4.5-py2.7.egg/bgmi/fetch.py", line 121, in bangumi_calendar
    print(' ' + bangumi['name'], ' ' * space_count, end='')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1-5: ordinal not in range(128)
ox@ox-Kaizaki:~/BGmi$ uname -a
Linux ox-Kaizaki 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by RicterZ** [comment]
讲道理，有点玄学啊…
试试用 python3 跑呢（

**Comment by yukiinagato** [comment]
唔……邮件进垃圾箱了Orz
今天才看到抱歉……
我想了一下可能是当初我偷懒配置 `Locale` 的时候 `$LC_ALL` 直接写了个 `C` 的原因……
试了一下
`export LC_ALL='en_US.utf8'`
然后就好了（
