### ISSUE TITLE
windows python2.7环境下，bgmi install安装xunlei-lixian失败

### ISSUE THREAD

**Issue by xtdyx001** [RicterZ/BGmi#39]
windows10下的python2.7，bgmi install安装xunlei-lixian失败
初学者，google了一下貌似是windows的问题？看readme说BGmi已经支持windows了应该没有这个问题呀

```
Traceback (most recent call last):
  File "C:\Python27\Scripts\bgmi-script.py", line 11, in <module>
    load_entry_point('bgmi==1.0.23', 'console_scripts', 'bgmi')()
  File "C:\Python27\lib\site-packages\bgmi-1.0.23-py2.7.egg\bgmi\main.py", line 157, in setup
    main()
  File "C:\Python27\lib\site-packages\bgmi-1.0.23-py2.7.egg\bgmi\main.py", line 124, in main
    bgmi.setup.install()
  File "C:\Python27\lib\site-packages\bgmi-1.0.23-py2.7.egg\bgmi\setup.py", line 35, in install
    get_download_class(DOWNLOAD_DELEGATE, instance=False).install()
  File "C:\Python27\lib\site-packages\bgmi-1.0.23-py2.7.egg\bgmi\services.py", line 203, in install
    os.symlink(os.path.join(BGMI_PATH, 'tools/xunlei-lixian/{0}/lixian_cli.py'.format(dir_name)),
AttributeError: 'module' object has no attribute 'symlink'
```
**更新**：参照[ http://stackoverflow.com/a/4388195/2197765]()解决了symlink的问题，现在的问题是
`Please run command 'C:\Users\xtdyx\.bgmi\bgmi-lx config' to configure your lixian-xunlei`
这个命令应该如何运行？cmd里面提示`'bgmi-lx' 不是内部或外部命令，也不是可运行的程序`

**Comment by RicterZ** [comment]
我这里容易修，不过 xunlei-lixian 不知道支不支持 windows..

**Comment by xtdyx001** [comment]
以上问题解决后运行`bgmi update --download`后有
```
 --verification-code-path=C:\Users\xtdyx\.bgmi\tmp\vcode.jpg
[-] Verification code path: C:\Users\xtdyx\.bgmi\tmp\vcode.jpg
[x] Error: environment can only contain strings
```
windows环境下无法显示验证码？看来 xunlei-lixian对windows支持应该还是有问题，还是用aria2好了。

**Comment by RicterZ** [comment]
嗯，aria2 大法好（
