### ISSUE TITLE
某些命令无法正常输出

### ISSUE THREAD

**Issue by trim21** [RicterZ/BGmi#52]
环境：Ubuntu 16.04.2 LTS 
Python 3.5.2
使用`bgmi cal all`
输出
```
Tue.
---------------------------------------   ---------------------------------------   ---------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/bgmi", line 11, in <module>
    sys.exit(setup())
  File "/usr/local/lib/python3.5/dist-packages/bgmi/main.py", line 163, in setup
    main()
  File "/usr/local/lib/python3.5/dist-packages/bgmi/main.py", line 135, in main
    controllers(ret)
  File "/usr/local/lib/python3.5/dist-packages/bgmi/controllers.py", line 290, in controllers
    return func(ret)
  File "/usr/local/lib/python3.5/dist-packages/bgmi/controllers.py", line 190, in cal
    bangumi_calendar(force_update=force, today=today, save=save)
  File "/usr/local/lib/python3.5/dist-packages/bgmi/fetch.py", line 122, in bangumi_calendar
    print(' ' + bangumi['name'], ' ' * space_count, end='')
  File "/usr/lib/python3.5/codecs.py", line 376, in write
    data, consumed = self.encode(object, self.errors)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1-6: ordinal not in range(128)
```
用一些其他的命令,比如` bgmi followed --list`也是同样的错误
是python版本的问题吗?

**Comment by RicterZ** [comment]
这是编码问题，晚点我去调试一下。 |ω•`)
Trim21 <notifications@github.com>于2017年5月30日 周二上午6:29写道：

**Comment by trim21** [comment]
似乎不是编码问题,在我运行了一段时间之后问题修复了,而且能正常输出内容了........
大概是某些内容没有下载下来,导致没内容可print..

**Comment by RicterZ** [comment]
错误是编码的错误……
这就有点迷了😨
Trim21 <notifications@github.com>于2017年5月30日 周二上午7:11写道：

**Comment by RicterZ** [comment]
蜜汁错误，下次遇到再修（。
