### ISSUE TITLE
python3 linux在第一次运行的时候无法选择数据源

### ISSUE THREAD

**Issue by trim21** [RicterZ/BGmi#86]
还没想到bug要怎么修,不过暂时解决的办法是有的..

解决方法..
选择[bangumi.moe](https://bangumi.moe/)做为数据源
```bash
rm ~/.bgmi -r
echo '1'|bgmi
```

选择[mikanani.me](https://mikanani.me/)做为数据源
```bash
rm ~/.bgmi -r
echo '2'|bgmi
```

**Comment by RicterZ** [comment]
直接默认bangumi.moe吧。
Trim21 <notifications@github.com>于2017年9月10日 周日下午6:58写道：

**Comment by trim21** [comment]
也是个好办法...
python3 mac的情况下没问题吗...

**Comment by RicterZ** [comment]
我还没测试，等会儿看完电影我回去看看是什么情况导致的

Trim21 <notifications@github.com>于2017年9月10日 周日下午7:02写道：

**Comment by trim21** [comment]
突然发现忘记贴报错了..
```
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pi/BGmi/bgmi/main.py", line 193, in <module>
    setup()
  File "/home/pi/BGmi/bgmi/main.py", line 181, in setup
    ds = input('select data source by input index: ')
  File "/usr/lib/python3.4/codecs.py", line 400, in __getattr__
    return getattr(self.stream, name)
AttributeError: '_io.BufferedWriter' object has no attribute 'encoding'
```
3.5的报错也是一样的..
